txt = "Daniel alberto VinZia"
print(txt.capitalize())
print(txt.casefold())
print(txt.encode())
print(txt.expandtabs())
print(txt.isalnum())
print(txt.isalpha())
print(txt.isascii())
print(txt.isdigit())
print(txt.isdigit())
print(txt.islower())
print(txt.isnumeric())
print(txt.isspace())
print(txt.istitle())
print(txt.isupper())
print(txt.lower())
print(txt.title())
print(txt.upper())